ALTER TABLE MOUBIENDBA.ARTWORK
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOUBIENDBA.ARTWORK CASCADE CONSTRAINTS;

CREATE TABLE MOUBIENDBA.ARTWORK
(
  ARTWORK_ID         NUMBER                     NOT NULL,
  CATALOGUE_NUMBER   NUMBER,
  TITLEOFWORK        VARCHAR2(200 BYTE),
  ARTIST             VARCHAR2(150 BYTE),
  COUNTRY_OF_ORGIIN  VARCHAR2(150 BYTE),
  DESCRIPTION        VARCHAR2(250 BYTE),
  YEAR_CREATED       VARCHAR2(50 BYTE)
)
;

CREATE UNIQUE INDEX MOUBIENDBA.ARTWORK_PK ON MOUBIENDBA.ARTWORK
(ARTWORK_ID)
LOGGING
TABLESPACE TBS_PERM_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MOUBIENDBA.ARTWORK ADD (
  CONSTRAINT ARTWORK_PK
  PRIMARY KEY
  (ARTWORK_ID)
  USING INDEX MOUBIENDBA.ARTWORK_PK
  ENABLE VALIDATE);
  
  
  SET DEFINE OFF;
Insert into MOUBIENDBA.ARTWORK
   (ARTWORK_ID, CATALOGUE_NUMBER, TITLEOFWORK, ARTIST, COUNTRY_OF_ORGIIN, 
    DESCRIPTION, YEAR_CREATED)
 Values
   (1, 711, 'Master', 'Ali', 'KSA', 
    'Ipusom DOlor', '1999');
Insert into MOUBIENDBA.ARTWORK
   (ARTWORK_ID, CATALOGUE_NUMBER, TITLEOFWORK, ARTIST, COUNTRY_OF_ORGIIN, 
    DESCRIPTION, YEAR_CREATED)
 Values
   (2, 711, 'The Sunset', 'Ali', 'KSA', 
    'Ipusom DOlor', '2005');
Insert into MOUBIENDBA.ARTWORK
   (ARTWORK_ID, CATALOGUE_NUMBER, TITLEOFWORK, ARTIST, COUNTRY_OF_ORGIIN, 
    DESCRIPTION, YEAR_CREATED)
 Values
   (3, 711, 'Under Surface', 'Husam', 'Yemen', 
    'Ipusom DOlor', '1977');
Insert into MOUBIENDBA.ARTWORK
   (ARTWORK_ID, CATALOGUE_NUMBER, TITLEOFWORK, ARTIST, COUNTRY_OF_ORGIIN, 
    DESCRIPTION, YEAR_CREATED)
 Values
   (4, 755, 'Monaliza', 'Picaso', 'Italy', 
    'Ipusom DOlor', '1850');
Insert into MOUBIENDBA.ARTWORK
   (ARTWORK_ID, CATALOGUE_NUMBER, TITLEOFWORK, ARTIST, COUNTRY_OF_ORGIIN, 
    DESCRIPTION, YEAR_CREATED)
 Values
   (5, 755, 'Queen', 'Mark', 'Spain', 
    'Ipusom DOlor', '2007');
Insert into MOUBIENDBA.ARTWORK
   (ARTWORK_ID, CATALOGUE_NUMBER, TITLEOFWORK, ARTIST, COUNTRY_OF_ORGIIN, 
    DESCRIPTION, YEAR_CREATED)
 Values
   (6, 800, 'Carpet', 'Yosuf', 'Syria', 
    'Ipusom DOlor', '2011');
COMMIT;

