ALTER TABLE MOUBIENDBA.BORROWED
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOUBIENDBA.BORROWED CASCADE CONSTRAINTS;

CREATE TABLE MOUBIENDBA.BORROWED
(
  B_ID              NUMBER,
  ARTWORD_ID_FK     NUMBER,
  COLLECTION_ID_FK  NUMBER,
  DATE_BOROWED      DATE,
  DATE_TO_RETURN    DATE
)
;


CREATE UNIQUE INDEX MOUBIENDBA.BORROWED_PK ON MOUBIENDBA.BORROWED
(B_ID)
LOGGING
TABLESPACE TBS_PERM_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MOUBIENDBA.BORROWED ADD (
  CONSTRAINT BORROWED_PK
  PRIMARY KEY
  (B_ID)
  USING INDEX MOUBIENDBA.BORROWED_PK
  ENABLE VALIDATE);

ALTER TABLE MOUBIENDBA.BORROWED ADD (
  CONSTRAINT ARTWORK_BOROW_FK 
  FOREIGN KEY (ARTWORD_ID_FK) 
  REFERENCES MOUBIENDBA.ARTWORK (ARTWORK_ID)
  ENABLE VALIDATE);
  
  
  
SET DEFINE OFF;
Insert into MOUBIENDBA.BORROWED
   (B_ID, ARTWORD_ID_FK, COLLECTION_ID_FK, DATE_BOROWED, DATE_TO_RETURN)
 Values
   (4, 4, 2, TO_DATE('03/19/2020', 'MM/DD/YYYY'), TO_DATE('03/26/2020', 'MM/DD/YYYY'));
Insert into MOUBIENDBA.BORROWED
   (B_ID, ARTWORD_ID_FK, COLLECTION_ID_FK, DATE_BOROWED, DATE_TO_RETURN)
 Values
   (3, 3, 1, TO_DATE('03/19/2020', 'MM/DD/YYYY'), TO_DATE('03/26/2020', 'MM/DD/YYYY'));
Insert into MOUBIENDBA.BORROWED
   (B_ID, ARTWORD_ID_FK, COLLECTION_ID_FK, DATE_BOROWED, DATE_TO_RETURN)
 Values
   (2, 2, 1, TO_DATE('03/19/2020', 'MM/DD/YYYY'), TO_DATE('03/26/2020', 'MM/DD/YYYY'));
Insert into MOUBIENDBA.BORROWED
   (B_ID, ARTWORD_ID_FK, COLLECTION_ID_FK, DATE_BOROWED, DATE_TO_RETURN)
 Values
   (1, 1, 1, TO_DATE('03/19/2020', 'MM/DD/YYYY'), TO_DATE('03/26/2020', 'MM/DD/YYYY'));
COMMIT;
