DROP TABLE MOUBIENDBA.EX_ART CASCADE CONSTRAINTS;

CREATE TABLE MOUBIENDBA.EX_ART
(
  ARTWORK_ID     NUMBER,
  EXHIBITION_ID  NUMBER
)
;

ALTER TABLE MOUBIENDBA.EX_ART ADD (
  CONSTRAINT EX_ART_R01 
  FOREIGN KEY (ARTWORK_ID) 
  REFERENCES MOUBIENDBA.ARTWORK (ARTWORK_ID)
  ENABLE VALIDATE,
  CONSTRAINT EX_ART_R02 
  FOREIGN KEY (EXHIBITION_ID) 
  REFERENCES MOUBIENDBA.EXHIBITION (EXHIBITION_ID)
  ENABLE VALIDATE);
  
  
SET DEFINE OFF;
Insert into MOUBIENDBA.EX_ART
   (ARTWORK_ID, EXHIBITION_ID)
 Values
   (3, 1);
Insert into MOUBIENDBA.EX_ART
   (ARTWORK_ID, EXHIBITION_ID)
 Values
   (1, 1);
Insert into MOUBIENDBA.EX_ART
   (ARTWORK_ID, EXHIBITION_ID)
 Values
   (2, 1);
Insert into MOUBIENDBA.EX_ART
   (ARTWORK_ID, EXHIBITION_ID)
 Values
   (5, 1);
Insert into MOUBIENDBA.EX_ART
   (ARTWORK_ID, EXHIBITION_ID)
 Values
   (5, 2);
Insert into MOUBIENDBA.EX_ART
   (ARTWORK_ID, EXHIBITION_ID)
 Values
   (1, 2);
Insert into MOUBIENDBA.EX_ART
   (ARTWORK_ID, EXHIBITION_ID)
 Values
   (2, 2);
COMMIT;
