ALTER TABLE MOUBIENDBA.EXHIBITION
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOUBIENDBA.EXHIBITION CASCADE CONSTRAINTS;

CREATE TABLE MOUBIENDBA.EXHIBITION
(
  EXHIBITION_ID    INTEGER                      NOT NULL,
  EXHIBITION_NAME  VARCHAR2(200 BYTE),
  STARTDATE        DATE                         DEFAULT sysdate,
  ENDDATE          DATE                         DEFAULT sysdate
)

;
CREATE UNIQUE INDEX MOUBIENDBA.EXHIBITION_PK ON MOUBIENDBA.EXHIBITION
(EXHIBITION_ID)
LOGGING
TABLESPACE TBS_PERM_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MOUBIENDBA.EXHIBITION ADD (
  CONSTRAINT EXHIBITION_PK
  PRIMARY KEY
  (EXHIBITION_ID)
  USING INDEX MOUBIENDBA.EXHIBITION_PK
  ENABLE VALIDATE);

ALTER TABLE MOUBIENDBA.EXHIBITION ADD (
  CONSTRAINT EXHIBITION_R01 
  FOREIGN KEY (EXHIBITION_ID) 
  REFERENCES MOUBIENDBA.EXHIBITION (EXHIBITION_ID)
  ENABLE VALIDATE);
  
  
SET DEFINE OFF;
Insert into MOUBIENDBA.EXHIBITION
   (EXHIBITION_ID, EXHIBITION_NAME, STARTDATE, ENDDATE)
 Values
   (1, 'Harthi', TO_DATE('03/27/2020', 'MM/DD/YYYY'), TO_DATE('03/31/2020', 'MM/DD/YYYY'));
Insert into MOUBIENDBA.EXHIBITION
   (EXHIBITION_ID, EXHIBITION_NAME, STARTDATE, ENDDATE)
 Values
   (2, 'Riyad', TO_DATE('03/27/2020', 'MM/DD/YYYY'), TO_DATE('04/03/2020', 'MM/DD/YYYY'));
COMMIT;
