ALTER TABLE MOUBIENDBA.PAINTING
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOUBIENDBA.PAINTING CASCADE CONSTRAINTS;

CREATE TABLE MOUBIENDBA.PAINTING
(
  PAINTING_ID    NUMBER,
  ARTWORK_ID_FK  NUMBER,
  TYPE_OF_PAINT  VARCHAR2(50 BYTE),
  MATERIAL       VARCHAR2(50 BYTE),
  STYLE          VARCHAR2(50 BYTE)
)
;


CREATE UNIQUE INDEX MOUBIENDBA.PAINTING_PK ON MOUBIENDBA.PAINTING
(PAINTING_ID)
LOGGING
TABLESPACE TBS_PERM_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MOUBIENDBA.PAINTING ADD (
  CONSTRAINT PAINTING_PK
  PRIMARY KEY
  (PAINTING_ID)
  USING INDEX MOUBIENDBA.PAINTING_PK
  ENABLE VALIDATE);

ALTER TABLE MOUBIENDBA.PAINTING ADD (
  CONSTRAINT PAINTING_R01 
  FOREIGN KEY (ARTWORK_ID_FK) 
  REFERENCES MOUBIENDBA.ARTWORK (ARTWORK_ID)
  ENABLE VALIDATE);
  
  
  
SET DEFINE OFF;
Insert into MOUBIENDBA.PAINTING
   (PAINTING_ID, ARTWORK_ID_FK, TYPE_OF_PAINT, MATERIAL, STYLE)
 Values
   (3, 2, 'Acrylic paint', 'Oil on copper', 'Modren');
Insert into MOUBIENDBA.PAINTING
   (PAINTING_ID, ARTWORK_ID_FK, TYPE_OF_PAINT, MATERIAL, STYLE)
 Values
   (2, 1, 'Aerosol paint', 'Oil on copper', 'Modren');
Insert into MOUBIENDBA.PAINTING
   (PAINTING_ID, ARTWORK_ID_FK, TYPE_OF_PAINT, MATERIAL, STYLE)
 Values
   (1, 6, 'Ink brush', 'Paper', 'Classic');
COMMIT;
