ALTER TABLE MOUBIENDBA.PERMANENT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOUBIENDBA.PERMANENT CASCADE CONSTRAINTS;

CREATE TABLE MOUBIENDBA.PERMANENT
(
  P_ID           NUMBER,
  DATE_ACQUIRE   DATE,
  COST           NUMBER,
  ARTWORK_ID_FK  NUMBER
)
;

CREATE UNIQUE INDEX MOUBIENDBA.PERMANENT_PK ON MOUBIENDBA.PERMANENT
(P_ID)
LOGGING
TABLESPACE TBS_PERM_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MOUBIENDBA.PERMANENT ADD (
  CONSTRAINT PERMANENT_PK
  PRIMARY KEY
  (P_ID)
  USING INDEX MOUBIENDBA.PERMANENT_PK
  ENABLE VALIDATE);

ALTER TABLE MOUBIENDBA.PERMANENT ADD (
  CONSTRAINT PERMANENT_R01 
  FOREIGN KEY (ARTWORK_ID_FK) 
  REFERENCES MOUBIENDBA.ARTWORK (ARTWORK_ID)
  ENABLE VALIDATE);
  
  SET DEFINE OFF;
Insert into MOUBIENDBA.PERMANENT
   (P_ID, DATE_ACQUIRE, COST, ARTWORK_ID_FK)
 Values
   (1, TO_DATE('03/27/2020', 'MM/DD/YYYY'), 3999, 5);
COMMIT;

