SELECT COUNT(*) FROM BORROWED 
INNER JOIN COLLECTION ON COLLETION_ID = COLLECTION_ID_FK
WHERE COLLETION_ID = 1
;

SELECT TYPE_OF_PAINT,MATERIAL, ARTIST,YEAR_CREATED
FROM PAINTING
INNER JOIN ARTWORK ON ARTWORK_ID =ARTWORK_ID_FK
;