ALTER TABLE MOUBIENDBA.SCULPTURE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MOUBIENDBA.SCULPTURE CASCADE CONSTRAINTS;

CREATE TABLE MOUBIENDBA.SCULPTURE
(
  SCULPTURE_ID   NUMBER,
  ARTWORK_ID_FK  NUMBER,
  MATERIAL       VARCHAR2(50 BYTE),
  HEIGHT         VARCHAR2(50 BYTE),
  WEIGHT         VARCHAR2(50 BYTE)
)
;


CREATE UNIQUE INDEX MOUBIENDBA.SCULPTURE_PK ON MOUBIENDBA.SCULPTURE
(SCULPTURE_ID)
LOGGING
TABLESPACE TBS_PERM_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MOUBIENDBA.SCULPTURE ADD (
  CONSTRAINT SCULPTURE_PK
  PRIMARY KEY
  (SCULPTURE_ID)
  USING INDEX MOUBIENDBA.SCULPTURE_PK
  ENABLE VALIDATE);

ALTER TABLE MOUBIENDBA.SCULPTURE ADD (
  CONSTRAINT SCULPTURE_R01 
  FOREIGN KEY (ARTWORK_ID_FK) 
  REFERENCES MOUBIENDBA.ARTWORK (ARTWORK_ID)
  ENABLE VALIDATE);
 
SET DEFINE OFF;
Insert into MOUBIENDBA.SCULPTURE
   (SCULPTURE_ID, ARTWORK_ID_FK, MATERIAL, HEIGHT, WEIGHT)
 Values
   (1, 5, 'Stone', '1.8', '200');
COMMIT;

